-- 영화 오펜하이머에 출현한 감독과 배우들을 조회하는 쿼리
-- 감독
SELECT
	MO_TITLE AS '영화제목',
    FP_NAME AS '영화인',
    RO_ROLE AS '역할'
FROM
	FILM_PERSON
		JOIN
	ROLE ON FP_NUM = RO_FP_NUM
        JOIN
	MOVIE ON MO_NUM = RO_MO_NUM
WHERE
	MO_TITLE = '오펜하이머';

-- 영화 기본 정보를 조회하는 쿼리
SELECT
	MO_TITLE AS 제목,
    MO_TITLE_ENG AS '제목(영문)',
    MO_OPENING_DATE AS 개봉일,
    CONCAT(MO_RUNNING_TIME,'분') AS 러닝타임,
    MO_PLOT AS 줄거리,
    MO_AG_NAME AS 연령제한,
    CONCAT(MO_RESERVATION_RATE,'%') AS 예매율
FROM
	MOVIE
WHERE
	MO_TITLE = '오펜하이머';

-- 영화 오펜하이머의 트레일러와 스틸컷 파일의 개수를 조회하는 쿼리
SELECT
	MO_TITLE AS 영화제목,
    FI_STATE AS 타입,
	COUNT(*) AS 개수
FROM
	FILE
		JOIN
	MOVIE_FILE ON FI_NUM = MF_FI_NUM
		JOIN
	MOVIE ON MO_NUM = MF_MO_NUM
WHERE
	MO_TITLE = '오펜하이머'
GROUP BY
	FI_STATE;

-- abc회원의 예매 내역을 조회하는 쿼리
SELECT
	MO_TITLE AS 영화제목, MS_START_TIME AS 상영시간, SE_NAME AS 좌석
FROM
	RESERVATION
		JOIN
	RESERVATION_LIST ON RV_NUM = RL_RV_NUM 
		JOIN
	SEAT ON SE_NUM = RL_SE_NUM
		JOIN
	MOVIE_SCHEDULE ON MS_NUM = RV_MS_NUM
		JOIN
	MOVIE ON MO_NUM = MS_MO_NUM
WHERE RV_ME_ID = 'abc123';

-- abc회원의 예매 내역을 조회하는 쿼리(영화명, 시간, 성인 x명, 청소년 x명)
SELECT
	MO_TITLE AS 영화제목, MS_START_TIME AS 상영시간,
    SUM(RV_ADULT) AS 성인수, SUM(RV_TEENAGER) AS 청소년수
FROM
	RESERVATION
		JOIN
	MOVIE_SCHEDULE ON MS_NUM = RV_MS_NUM
		JOIN
	MOVIE ON MO_NUM = MS_MO_NUM
WHERE RV_ME_ID = 'abc123';

-- CGV강남 영화관에서 콘크리트 유토피아 20:50에 예매 가능한 좌석을 조회하는 쿼리
SELECT
	SE_NAME
FROM
	SEAT
		JOIN
	SCREEN ON SC_NUM = SE_SC_NUM
		JOIN
	MOVIE_SCHEDULE ON SC_NUM = MS_SC_NUM
WHERE
	MS_NUM = 8 AND SE_NUM NOT IN(
		SELECT RL_SE_NUM FROM RESERVATION
			JOIN RESERVATION_LIST ON RV_NUM = RL_RV_NUM
			WHERE RV_MS_NUM = 8
    );

SELECT
	SE_NAME
FROM
	SEAT
    	JOIN
	SCREEN ON SC_NUM = SE_SC_NUM
    	JOIN
	MOVIE_SCHEDULE ON SC_NUM = MS_SC_NUM
		JOIN
	MOVIE ON MO_NUM = MS_MO_NUM
		LEFT JOIN
	RESERVATION_LIST ON SE_NUM = RL_SE_NUM    
WHERE MO_TITLE = '콘크리트 유토피아' AND MS_START_TIME = '20:50:00' AND SE_NAME NOT IN(
		SELECT SE_NAME FROM RESERVATION
			JOIN RESERVATION_LIST ON RV_NUM = RL_RV_NUM
            JOIN SEAT ON SE_NUM = RL_SE_NUM
			WHERE RV_MS_NUM = 8
    );